Car management/force-app/main/default/objects/Pojazd__c/Pojazd__c.object-meta.xml
<CustomObject>
    <label>Pojazd</label>
    <nameField>
        <label>Numer Pojazdu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pojazdy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Pojazd__c/fields/Numer_seryjny__c.field-meta.xml
<CustomField>
    <fullName>Numer_seryjny__c</fullName>
    <label>Numer seryjny</label>
    <length>17</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Car management/force-app/main/default/objects/Telemetry__c/Telemetry__c.object-meta.xml
<CustomObject>
    <label>Telemetry</label>
    <nameField>
        <label>Telemetry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telemeties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Telemetry__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Telemeties</relationshipLabel>
    <relationshipName>Telemeties</relationshipName>
    <type>Lookup</type>
</CustomField>

Car management/force-app/main/default/classes/CarDeleteInfoTest.cls
@isTest
private class CarDeleteInfoTest {

    @isTest static void testDeleteWithTelemetry(){
        List<Pojazd__c> car=new List<Pojazd__c>();
        List<Telemetry__c> tele=new List<Telemetry__c>();

        for(Integer i=0;i<200;i++){
           car.add( new Pojazd__c(Name=i+'',Numer_seryjny__c=i+''));
        }

        if(car.size()>0){
            insert car;
        }

        for(Pojazd__c c:car){
            tele.add( new Telemetry__c(Pojazd__c=c.id,name='teleName1'));
        }



        if(car.size()>0){
            insert tele;
        }

        Test.startTest();
        List<Database.DeleteResult> result = Database.delete(car);
        Test.stopTest();

        for(Database.DeleteResult r:result){
            System.assert(r.isSuccess(),true);
        }

        List<Telemetry__c> telemetryList = [Select Id from Telemetry__c];
        System.assert(telemetryList.size()==0);
    }
    
}