Car management/force-app/main/default/objects/Salon__c/Salon__c.object-meta.xml
<CustomObject>
    <label>Salon</label>
    <nameField>
        <label>Nazwa Salonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salony</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Salon__c/fields/Salon_status__c.field-meta.xml
<CustomField>
    <fullName>Salon_status__c</fullName>
    <label>Salon status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Open day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samochody osobowe</fullName>
                <default>true</default>
                <label>Samochody osobowe</label>
            </value>
            <value>
                <fullName>Samochody specjalistyczne</fullName>
            </value>
            <value>
                <fullName>Wszystkie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Wlasciciel__c.field-meta.xml
<CustomField>
    <fullName>Wlasciciel__c</fullName>
    <label>Właściciel</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salony (Właściciel)</relationshipLabel>
    <relationshipName>Salony2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/classes/CaseSalonHandlerTest.cls
/**
* @author kamil.wisniewski@accenture.com
* @date 02/02/2022
* @description The class is the test CloseSalon trigger
 **/
@isTest
public class CaseSalonHandlerTest implements Database.AllowsCallouts {

    public class ExampleCalloutMock implements HttpCalloutMock{
        public HttpResponse respond(HTTPRequest req){
            HttpResponse res = new HttpResponse();
            res.setStatus('OK');
            res.setStatusCode(201);
            res.setBody('Salesforcescool');
            return res;
        }
    }
    
    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method test case insert
    **/
    @isTest
    public static void insertSalon(){
        List<Salon__c> salonList=new List<Salon__c>();
        Account newAccount=new Account(Name='Name');
        insert newAccount;
        Salon__c newSalon= new Salon__c(Name='Name',Salon_status__c='Open',Typ__c='Wszystkie',Wlasciciel__c=newAccount.id);
        insert newSalon;
        salonList.add(newSalon);
        newSalon.Salon_status__c='Close';
        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ExampleCalloutMock());
        update newSalon;
        Test.stopTest();
		
        List<Case> caseList= [SELECT Id FROM Case];
        System.assert(caseList.size()>0);

    }    

    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method test update case
    **/
    @isTest
    public static void updateCase(){

        Account newAccount=new Account(Name='Name');
        insert newAccount;
        Salon__c newSalon= new Salon__c(Name='Name',Salon_status__c='Open',Typ__c='Wszystkie',Wlasciciel__c=newAccount.id);
        insert newSalon;
        Case newCase=new Case(Origin='WEB',Salon__c=newSalon.ID,Subject = 'Renovation Case');
        List<Case> caseList=new List<Case>();
        caseList.add(newCase);

        Test.startTest();
        Test.setMock(HttpCalloutMock.class, new ExampleCalloutMock());
        insert caseList;
        CloseSalonCaseUpdate caseUpdate = new CloseSalonCaseUpdate(caseList);
        Id jobId = System.enqueueJob(caseUpdate);
        Test.stopTest();

        System.assert(jobId!=null);
    }

    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method test null Insert
    **/
    @isTest
    public static void nullInsert(){
        CloseSalonHandler handlerClass = new CloseSalonHandler(null);
        System.assert(true);
    }

    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method test null update
    **/
    @isTest
    public static void nullUpdate(){
        CloseSalonCaseUpdate caseUpdate = new CloseSalonCaseUpdate(null);
        System.assert(true);
    }

}