Car management/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oferty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Oferta__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/Pojazd__c.object-meta.xml
<CustomObject>
    <label>Pojazd</label>
    <nameField>
        <label>Numer Pojazdu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pojazdy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Pojazd__c/fields/Marka__c.field-meta.xml
<CustomField>
    <fullName>Marka__c</fullName>
    <label>Marka</label>
    <length>30</length>
    <type>Text</type>
</CustomField>

Car management/force-app/main/default/objects/Telemetry__c/Telemetry__c.object-meta.xml
<CustomObject>
    <label>Telemetry</label>
    <nameField>
        <label>Telemetry Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Telemeties</pluralLabel>
    <sharingModel>Private</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Telemetry__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Telemeties</relationshipLabel>
    <relationshipName>Telemeties</relationshipName>
    <type>Lookup</type>
</CustomField>

Car management/force-app/main/default/classes/CarDeleteInfoHandler.cls
/**
* @author kamil.wisniewski@accenture.com
* @date 31/01/2022
* @description The class is the handler to the trigger before insert Oferta__c
 **/

public with sharing class CarDeleteInfoHandler {



    /**
     * @author kamil.wisniewski@accenture.com
     * @date 31/01/2022
     * @description The method delete telemetry for the deleted car and adds an case to the database
     **/
    public static void check(List<Pojazd__c> inCar){
        

    if(inCar.size()>0){
        List<Telemetry__c> telemetries=[SELECT Id from Telemetry__c where Pojazd__c IN :inCar];
        delete telemetries;
    }

    

    List <Case> caseList= new List<Case>();
    

    for(Pojazd__c c:inCar){
        List <String> strList = new List < String > { c.Marka__c, c.Model__c };  
        String carDescription = String.join( strList, ', ' );  
        caseList.add(new Case(Description = carDescription,Reason='Other',Status='New',Origin='Web',Priority='High'));
    }

    insert caseList;

    }

}