Car management/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oferty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Oferta__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Oferta__c/fields/Salon__c.field-meta.xml
<CustomField>
    <fullName>Salon__c</fullName>
    <label>Salon</label>
    <referenceTo>Salon__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Oferta__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Oferta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wirtualna</fullName>
                <default>true</default>
                <label>Wirtualna</label>
            </value>
            <value>
                <fullName>Fizyczna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/Pojazd__c.object-meta.xml
<CustomObject>
    <label>Pojazd</label>
    <nameField>
        <label>Numer Pojazdu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pojazdy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Pojazd__c/fields/Numer_seryjny__c.field-meta.xml
<CustomField>
    <fullName>Numer_seryjny__c</fullName>
    <label>Numer seryjny</label>
    <length>17</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Stan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nowy</fullName>
                <default>true</default>
                <label>Nowy</label>
            </value>
            <value>
                <fullName>Gotowy do sprzedaży</fullName>
            </value>
            <value>
                <fullName>Sprzedany</fullName>
            </value>
            <value>
                <fullName>W naprawie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/Salon__c.object-meta.xml
<CustomObject>
    <label>Salon</label>
    <nameField>
        <label>Nazwa Salonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salony</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Salon__c/fields/Salon_status__c.field-meta.xml
<CustomField>
    <fullName>Salon_status__c</fullName>
    <label>Salon status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Open day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samochody osobowe</fullName>
                <default>true</default>
                <label>Samochody osobowe</label>
            </value>
            <value>
                <fullName>Samochody specjalistyczne</fullName>
            </value>
            <value>
                <fullName>Wszystkie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Wlasciciel__c.field-meta.xml
<CustomField>
    <fullName>Wlasciciel__c</fullName>
    <label>Właściciel</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salony (Właściciel)</relationshipLabel>
    <relationshipName>Salony2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/classes/CheckOfferTest.cls
/**
* @author kamil.wisniewski@accenture.com
* @date 31/01/2022
* @description The class is the test CheckOffer trigger
 **/

@isTest
private class CheckOfferTest {



    /**
    * @author kamil.wisniewski@accenture.com
    * @date 31/01/2022
    * @description The method tests insert correct offers
    **/
    @isTest static void testSinglePhysicalCar(){

        List<Pojazd__c> vehicleList=new List<Pojazd__C>();
        List<Salon__c> salonList = new List<Salon__c>();
        List<Oferta__c> offerList = new List<Oferta__c>();

        for(Integer i=0;i<200;i++){
            vehicleList.add(new Pojazd__c(Name='CarName'+i,Numer_seryjny__c='serialNumber'+i));
        }
        insert vehicleList;

        Account account=new Account(Name='Accname');
        insert account;


        for(Integer i=0;i<200;i++){
            salonList.add(new Salon__c(name='SalonName'+i,Salon_status__c='open',Typ__c='Wszystkie',Wlasciciel__c=account.id));
        }
        insert salonList;


        for(Integer i=0;i<200;i++){
        
            offerList.add(new Oferta__c(name='of1'+i,Pojazd__c=vehicleList.get(i).id,Stan__c=Constant.PHYSICAL,Salon__c=salonList.get(i).id));
        }

        Test.startTest();
        List<Database.SaveResult> result = Database.insert(offerList);
        Test.stopTest();


        for(Database.SaveResult r:result){
            System.assert(r.isSuccess(),true);
        }

    }


    /**
    * @author kamil.wisniewski@accenture.com
    * @date 31/01/2022
    * @description The method tests insert 2 phisical offer with the same vehicle
    **/
    @isTest static void testDoublePhysicalCar(){
    
        Pojazd__c vehicle = new Pojazd__c(Name='CarName',Numer_seryjny__c='serialNumber');
        insert vehicle;

        Account account=new Account(Name='Accname');
        insert account;

        Salon__c salon= new Salon__c(name='SalonName',Salon_status__c='open',Typ__c='Wszystkie',Wlasciciel__c=account.id);
        insert salon;


        Oferta__c correctOffer= new Oferta__c(name='offer',Pojazd__c=vehicle.id,Stan__c=Constant.PHYSICAL,Salon__c=salon.id);
        insert correctOffer;

        Oferta__c wrongOffer= new Oferta__c(name='of2',Pojazd__c=vehicle.id,Stan__c=Constant.PHYSICAL,Salon__c=salon.id);

        Test.startTest();
        Database.SaveResult result = Database.insert(wrongOffer,false);
        Test.stopTest();

        System.assertEquals(result.isSuccess(),false);
        System.assert(result.getErrors().size() > 0);
        System.assertEquals('You can not set again this car as physical', result.getErrors()[0].getMessage());
    
    }

    /**
    * @author kamil.wisniewski@accenture.com
    * @date 31/01/2022
    * @description The method tests insert 2 of the same offers
    **/
    @isTest static void testSameCar(){

        Pojazd__c vehicle = new Pojazd__c(Name='CarName',Numer_seryjny__c='serialNumber');
        insert vehicle;

        Account account=new Account(Name='Accname');
        insert account;

        Salon__c salon= new Salon__c(name='SalonName',Salon_status__c='open',Typ__c='Wszystkie',Wlasciciel__c=account.id);
        insert salon;



        Oferta__c correctOffer= new Oferta__c(name='of1',Pojazd__c=vehicle.id,Stan__c=Constant.PHYSICAL,Salon__c=salon.id);		
        Oferta__c wrongOffer=new Oferta__c(name='of1',Pojazd__c=vehicle.id,Stan__c=Constant.PHYSICAL,Salon__c=salon.id);

        List <Oferta__c> offerList = new List<Oferta__c>();
        offerList.add(correctOffer);
        offerList.add(wrongOffer);
        Test.startTest();
        List<Database.SaveResult> result = Database.insert(offerList,false);
        Test.stopTest();

        List<Oferta__c> offList =[SELECT Id from Oferta__c];
        System.assert(offList.size()==1);
    }


    /**
    * @author kamil.wisniewski@accenture.com
    * @date 01/02/2022
    * @description The method tests null insert 
    **/
    @isTest static void testNullCar(){

        Test.startTest();
        CarDeleteInfoHandler.carDeleteCleanup(null);
        Test.stopTest();

    }


}