Car management/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oferty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Oferta__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Oferta__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Oferta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wirtualna</fullName>
                <default>true</default>
                <label>Wirtualna</label>
            </value>
            <value>
                <fullName>Fizyczna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/Pojazd__c.object-meta.xml
<CustomObject>
    <label>Pojazd</label>
    <nameField>
        <label>Numer Pojazdu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pojazdy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Pojazd__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Stan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nowy</fullName>
                <default>true</default>
                <label>Nowy</label>
            </value>
            <value>
                <fullName>Gotowy do sprzedaży</fullName>
            </value>
            <value>
                <fullName>Sprzedany</fullName>
            </value>
            <value>
                <fullName>W naprawie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/classes/CheckOfferHandler.cls
/**
     * @author kamil.wisniewski@accenture.com
     * @date 31/01/2022
     * @description The class is the handler to the trigger before delete Pojazd__c
     **/


public with sharing class CheckOfferHandler {


    /**
     * @author kamil.wisniewski@accenture.com
     * @date 31/01/2022
     * @description The method checks if there is no other physical offer for the vehicle
     **/
    public static void checkOffer(List<Oferta__c> inOfferList){
        

        List<Oferta__c> offerList= new List<Oferta__c>();
        List<Id> vehicleIdList= new List<Id>();


        if(inOfferList==null){
            return;
        }
        

        for(Oferta__c offer: inOfferList){
            if(offer.Stan__c == Constant.PHYSICAL){
                offerList.add(offer);
                vehicleIdList.add(offer.Pojazd__c);
            }
        }

        List<Oferta__c> phisicalCheck = [SELECT Pojazd__c FROM Oferta__c WHERE Pojazd__c IN :vehicleIdList AND Stan__c =:Constant.PHYSICAL];


        Integer count;
        for(Oferta__C offer:offerList){
            count=0;

            for(Oferta__c phisicalOffer:phisicalCheck){

                if(offer.Pojazd__c==phisicalOffer.Pojazd__c){
                    offer.addError('You can not set again this car as physical');
                    break;
                }else{
                    count++;
                }
            }

            if(count==phisicalCheck.size()){
                phisicalCheck.add(offer);
            }

        }

    }

}