Car management/force-app/main/default/objects/Oferta__c/Oferta__c.object-meta.xml
<CustomObject>
    <label>Oferta</label>
    <nameField>
        <label>Oferta Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Oferty</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Oferta__c/fields/Pojazd__c.field-meta.xml
<CustomField>
    <fullName>Pojazd__c</fullName>
    <label>Pojazd</label>
    <referenceTo>Pojazd__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Oferta__c/fields/Salon__c.field-meta.xml
<CustomField>
    <fullName>Salon__c</fullName>
    <label>Salon</label>
    <referenceTo>Salon__c</referenceTo>
    <relationshipLabel>Oferty</relationshipLabel>
    <relationshipName>Oferty</relationshipName>
    <relationshipOrder>1</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/objects/Oferta__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Oferta</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Wirtualna</fullName>
                <default>true</default>
                <label>Wirtualna</label>
            </value>
            <value>
                <fullName>Fizyczna</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/Pojazd__c.object-meta.xml
<CustomObject>
    <label>Pojazd</label>
    <nameField>
        <label>Numer Pojazdu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Pojazdy</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Pojazd__c/fields/Numer_seryjny__c.field-meta.xml
<CustomField>
    <fullName>Numer_seryjny__c</fullName>
    <label>Numer seryjny</label>
    <length>17</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Car management/force-app/main/default/objects/Pojazd__c/fields/Stan__c.field-meta.xml
<CustomField>
    <fullName>Stan__c</fullName>
    <label>Stan</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Nowy</fullName>
                <default>true</default>
                <label>Nowy</label>
            </value>
            <value>
                <fullName>Gotowy do sprzedaży</fullName>
            </value>
            <value>
                <fullName>Sprzedany</fullName>
            </value>
            <value>
                <fullName>W naprawie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/Salon__c.object-meta.xml
<CustomObject>
    <label>Salon</label>
    <nameField>
        <label>Nazwa Salonu</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Salony</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Car management/force-app/main/default/objects/Salon__c/fields/Salon_status__c.field-meta.xml
<CustomField>
    <fullName>Salon_status__c</fullName>
    <label>Salon status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Open</fullName>
            </value>
            <value>
                <fullName>Close</fullName>
            </value>
            <value>
                <fullName>Open day</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Typ__c.field-meta.xml
<CustomField>
    <fullName>Typ__c</fullName>
    <label>Typ</label>
    <required>true</required>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>Samochody osobowe</fullName>
                <default>true</default>
                <label>Samochody osobowe</label>
            </value>
            <value>
                <fullName>Samochody specjalistyczne</fullName>
            </value>
            <value>
                <fullName>Wszystkie</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

Car management/force-app/main/default/objects/Salon__c/fields/Wlasciciel__c.field-meta.xml
<CustomField>
    <fullName>Wlasciciel__c</fullName>
    <label>Właściciel</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Salony (Właściciel)</relationshipLabel>
    <relationshipName>Salony2</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Car management/force-app/main/default/classes/NewOfferTest.cls
/**
* @author kamil.wisniewski@accenture.com
* @date 02/02/2022
* @description The class is the test NewOffer trigger
 **/
@isTest
public class NewOfferTest {
    
    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method checks if the method was called
    **/    
    @isTest
    private static void testInsertNewOffer(){

        List<Oferta__c> offerList = new List<Oferta__c>();

        Pojazd__c vehicle = new Pojazd__c(Name='CarName',Numer_seryjny__c='serialNumber');
        insert vehicle;

        Account account=new Account(Name='Accname');
        insert account;

        Salon__c salon= new Salon__c(name='SalonName',Salon_status__c='open',Typ__c='Wszystkie',Wlasciciel__c=account.id);
        insert salon;

        for(Integer i=0;i<200;i++){
            offerList.add(new Oferta__c(name='offer',Pojazd__c=vehicle.id,Stan__c='Wirtualna',Salon__c=salon.id));
        }

        Test.startTest();
        insert offerList;
        Integer futureCount = Limits.getFutureCalls();
        Test.stopTest();

        
        System.assert(futureCount>0);
    }
    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method checks null offer
    **/    
    @isTest
    private static void testNullOffer(){
        NewOfferHandler.sendId(null);
        System.assert(true);
    }
    /**
    * @author kamil.wisniewski@accenture.com
    * @date 02/02/2022
    * @description The method checks null casess
    **/    
    @isTest
    private static void testSendNullId(){
        SendMailFuture.sendmail(null);
        System.assert(true);
    }
}